version: '3'

services:
  tutorial-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped